#!/usr/bin/env bash
# install.sh — MailDome interactive installer
#
# Usage (from repo root):
#   bash install.sh
#
# Usage (one-liner, clones repo automatically):
#   curl -sSL https://raw.githubusercontent.com/LaPocheduKangaroo/Maildome/main/install.sh | bash
#
# The script asks 5 questions, recommends a deployment tier, generates
# secrets, writes .env and docker-compose.override.yml, then starts the
# stack with docker compose.

set -euo pipefail

# ── Sourceable guard (for unit tests) ────────────────────────────────────────
# When MAILDOME_TEST=1, only function definitions are loaded; main() is not called.
_MAILDOME_TEST="${MAILDOME_TEST:-0}"

# ── Terminal colours ──────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
  BLUE='\033[0;34m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; DIM=''; NC=''
fi

# ── Helpers ───────────────────────────────────────────────────────────────────

die()  { echo -e "${RED}error:${NC} $*" >&2; exit 1; }
info() { echo -e "${BLUE}  →${NC} $*"; }
ok()   { echo -e "${GREEN}  ✓${NC} $*"; }
warn() { echo -e "${YELLOW}  !${NC} $*"; }
section() { echo -e "\n${BOLD}$*${NC}"; }

ask() {
  # ask <varname> <prompt> [default]
  local varname="$1" prompt="$2" default="${3:-}"
  local full_prompt
  if [[ -n "$default" ]]; then
    full_prompt="${prompt} [${DIM}${default}${NC}]: "
  else
    full_prompt="${prompt}: "
  fi
  read -r -p "$(echo -e "$full_prompt")" "$varname" </dev/tty
  # Apply default when answer is blank
  if [[ -z "${!varname}" && -n "$default" ]]; then
    printf -v "$varname" '%s' "$default"
  fi
}

ask_secret() {
  # ask_secret <varname> <prompt>
  local varname="$1" prompt="$2"
  read -r -s -p "$(echo -e "${prompt}: ")" "$varname" </dev/tty
  echo
}

# Generate a cryptographically random hex string of <bytes> bytes.
gen_secret() {
  local bytes="${1:-32}"
  openssl rand -hex "$bytes"
}

# ── Tier recommendation ───────────────────────────────────────────────────────

# recommend_tier <user_band> <has_executives>
# user_band: "small" (1-50) | "medium" (51-200) | "large" (200+)
# has_executives: "y" | "n"
# Prints: "Basic" | "Advanced" | "Premium"
recommend_tier() {
  local band="$1" exec="$2"
  if [[ "$band" == "large" ]]; then
    if [[ "$exec" == "y" ]]; then
      echo "Premium"
    else
      echo "Advanced"
    fi
  elif [[ "$band" == "medium" || "$exec" == "y" ]]; then
    echo "Advanced"
  else
    echo "Basic"
  fi
}

# ── Config writers ────────────────────────────────────────────────────────────

# write_env <dest> <vars...> — write a KEY=value .env file
# Called as: write_env /path/.env KEY1 VAL1 KEY2 VAL2 ...
write_env() {
  local dest="$1"; shift
  {
    echo "# MailDome — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Do NOT commit this file to git."
    echo ""
    while [[ $# -ge 2 ]]; do
      echo "${1}=${2}"
      shift 2
    done
  } > "$dest"
}

# patch_conf <conf_file> <section> <key> <value>
# Replace "key = ..." inside [section] in a .conf file.
patch_conf() {
  local file="$1" section="$2" key="$3" value="$4"
  # Use awk: inside the target section, replace the key; elsewhere pass through.
  awk -v sec="[$section]" -v k="$key" -v v="$value" '
    /^\[/ { in_sec = ($0 == sec) }
    in_sec && $0 ~ "^" k " *= *" { $0 = k " = " v }
    { print }
  ' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
}

# write_override <dest> <mail_domain> <conf_path_in_container>
write_override() {
  local dest="$1" mail_domain="$2" conf_path="$3"
  cat > "$dest" <<EOF
# docker-compose.override.yml — generated by install.sh
# Overrides that complement docker-compose.yml for this installation.
# Do NOT commit this file to git.
version: '3.9'
services:
  postfix:
    environment:
      - ALLOWED_SENDER_DOMAINS=${mail_domain}
  acquisition:
    environment:
      - MAILSHIELD_CONFIG=${conf_path}
  celery_worker:
    environment:
      - MAILSHIELD_CONFIG=${conf_path}
  api:
    environment:
      - MAILSHIELD_CONFIG=${conf_path}
      - API_TOKEN=\${API_TOKEN}
EOF
}

# ── Prerequisite checks ───────────────────────────────────────────────────────

check_prereqs() {
  section "Checking prerequisites"

  command -v docker &>/dev/null || die "Docker is not installed. See https://docs.docker.com/engine/install/"
  ok "docker found ($(docker --version | head -1))"

  if docker compose version &>/dev/null 2>&1; then
    COMPOSE="docker compose"
  elif command -v docker-compose &>/dev/null; then
    COMPOSE="docker-compose"
  else
    die "Docker Compose not found. Run: apt-get install docker-compose-plugin"
  fi
  ok "docker compose found ($COMPOSE)"

  command -v openssl &>/dev/null || die "openssl is required for secret generation"
  ok "openssl found"
}

# ── Repo bootstrap (curl | bash case) ────────────────────────────────────────

ensure_repo() {
  if [[ ! -f "docker-compose.yml" ]]; then
    section "Cloning MailDome repository"
    command -v git &>/dev/null || die "git is required"
    git clone https://github.com/LaPocheduKangaroo/Maildome.git maildome
    cd maildome
    ok "Repository cloned into ./maildome"
  fi
}

# ── Wait for the API to become healthy ───────────────────────────────────────

wait_healthy() {
  local url="$1" retries="${2:-30}" delay="${3:-3}"
  info "Waiting for API at ${url}/api/v1/status …"
  local i=0
  while (( i < retries )); do
    if curl -sf "${url}/api/v1/status" -o /dev/null 2>/dev/null; then
      ok "API is up."
      return 0
    fi
    (( i++ ))
    sleep "$delay"
  done
  warn "API did not respond after $(( retries * delay ))s — check: $COMPOSE logs api"
  return 1
}

# ── Main installer ────────────────────────────────────────────────────────────

main() {
  echo -e "${BOLD}"
  echo "  ███╗   ███╗ █████╗ ██╗██╗     ██████╗  ██████╗ ███╗   ███╗███████╗"
  echo "  ████╗ ████║██╔══██╗██║██║     ██╔══██╗██╔═══██╗████╗ ████║██╔════╝"
  echo "  ██╔████╔██║███████║██║██║     ██║  ██║██║   ██║██╔████╔██║█████╗  "
  echo "  ██║╚██╔╝██║██╔══██║██║██║     ██║  ██║██║   ██║██║╚██╔╝██║██╔══╝  "
  echo "  ██║ ╚═╝ ██║██║  ██║██║███████╗██████╔╝╚██████╔╝██║ ╚═╝ ██║███████╗"
  echo "  ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝╚══════╝╚═════╝  ╚═════╝ ╚═╝     ╚═╝╚══════╝"
  echo -e "${NC}"
  echo "  Email security platform — installer v1.0"
  echo ""

  check_prereqs
  ensure_repo

  # ── Question 1 — Mail domain ────────────────────────────────────────────────
  section "Question 1 / 5 — Mail domain"
  echo "  The primary domain your organisation sends and receives email on."
  echo ""
  ask MAIL_DOMAIN "  Mail domain (e.g. company.com)" "example.com"

  # ── Question 2 — User count ─────────────────────────────────────────────────
  section "Question 2 / 5 — Number of protected mailboxes"
  echo "  1) 1–50 mailboxes"
  echo "  2) 51–200 mailboxes"
  echo "  3) 201+ mailboxes"
  echo ""
  ask USER_BAND_CHOICE "  Choose [1/2/3]" "1"
  case "$USER_BAND_CHOICE" in
    1) USER_BAND="small"  ;;
    2) USER_BAND="medium" ;;
    3) USER_BAND="large"  ;;
    *) warn "Unrecognised choice — defaulting to small"; USER_BAND="small" ;;
  esac

  # ── Question 3 — Executive accounts ─────────────────────────────────────────
  section "Question 3 / 5 — Executive / finance accounts"
  echo "  Do executive, finance, or legal staff receive email on this domain?"
  echo "  (Enables BEC-detection weighting in the Advanced tier.)"
  echo ""
  ask HAS_EXEC "  Are there high-value targets? [y/N]" "n"
  HAS_EXEC="${HAS_EXEC,,}"   # lowercase
  [[ "$HAS_EXEC" =~ ^(y|yes)$ ]] && HAS_EXEC="y" || HAS_EXEC="n"

  # ── Tier recommendation ──────────────────────────────────────────────────────
  TIER=$(recommend_tier "$USER_BAND" "$HAS_EXEC")
  section "Recommended tier: ${GREEN}${TIER}${NC}"
  case "$TIER" in
    Basic)
      echo "  Pipeline: L0 Acquisition → L1 Static Analysis → L5 Decision Engine"
      echo "  Verdict display: 3 states (CLEAN / SUSPICIOUS / DANGEROUS)"
      ;;
    Advanced)
      echo "  Pipeline: L0 → L1 → L2 Sender Behaviour → L3 Attachment Triage → L5"
      warn "  Advanced tier is not yet implemented — deploying Basic for now."
      TIER="Basic"
      ;;
    Premium)
      echo "  Pipeline: L0 → … → L4 VM Sandbox → L5"
      warn "  Premium tier is not yet implemented — deploying Basic for now."
      TIER="Basic"
      ;;
  esac
  echo ""
  ask _CONFIRM "  Deploy ${TIER}? [Y/n]" "y"
  [[ "${_CONFIRM,,}" =~ ^(n|no)$ ]] && { echo "Aborted."; exit 0; }

  # ── Question 4 — IMAP account ────────────────────────────────────────────────
  section "Question 4 / 5 — IMAP scanning account"
  echo "  MailDome needs a dedicated mailbox that receives journal/BCC copies."
  echo ""
  ask IMAP_HOST "  IMAP server host" "mail.${MAIL_DOMAIN}"
  ask IMAP_PORT "  IMAP port" "993"
  ask IMAP_USER "  IMAP username" "maildome@${MAIL_DOMAIN}"
  ask_secret IMAP_PASSWORD "  IMAP password"

  # ── Question 5 — Admin email ──────────────────────────────────────────────────
  section "Question 5 / 5 — Admin email (optional)"
  echo "  Used for degraded-state and DANGEROUS-verdict notifications."
  echo ""
  ask ADMIN_EMAIL "  Admin email (leave blank to skip)" ""

  # ── Generate secrets ──────────────────────────────────────────────────────────
  section "Generating secrets"
  PG_PASSWORD=$(gen_secret 24)
  REDIS_PASSWORD=$(gen_secret 24)
  API_TOKEN=$(gen_secret 32)
  ok "PostgreSQL password generated"
  ok "Redis password generated"
  ok "API token generated"

  # ── Write .env ────────────────────────────────────────────────────────────────
  section "Writing .env"
  write_env ".env" \
    POSTGRES_DB      "maildome" \
    POSTGRES_USER    "maildome" \
    POSTGRES_PASSWORD "$PG_PASSWORD" \
    REDIS_PASSWORD   "$REDIS_PASSWORD" \
    IMAP_PASSWORD    "$IMAP_PASSWORD" \
    API_TOKEN        "$API_TOKEN" \
    MAIL_DOMAIN      "$MAIL_DOMAIN"
  ok ".env written (keep this file secret — never commit it)"

  # ── Patch mailshield.conf ─────────────────────────────────────────────────────
  section "Updating mailshield.conf"
  CONF="core/config/mailshield.conf"
  patch_conf "$CONF" acquisition imap_host      "$IMAP_HOST"
  patch_conf "$CONF" acquisition imap_port      "$IMAP_PORT"
  patch_conf "$CONF" acquisition imap_user      "$IMAP_USER"
  patch_conf "$CONF" acquisition imap_mailbox   "INBOX"
  if [[ -n "$ADMIN_EMAIL" ]]; then
    patch_conf "$CONF" notifications admin_email "$ADMIN_EMAIL"
  fi
  ok "core/config/mailshield.conf updated"

  # ── Write docker-compose.override.yml ────────────────────────────────────────
  section "Writing docker-compose.override.yml"
  write_override "docker-compose.override.yml" \
    "$MAIL_DOMAIN" \
    "/app/core/config/mailshield.conf"
  ok "docker-compose.override.yml written"

  # ── Build and start ───────────────────────────────────────────────────────────
  section "Building and starting MailDome"
  $COMPOSE up -d --build
  ok "Containers started"

  # ── Health check ──────────────────────────────────────────────────────────────
  wait_healthy "http://localhost:8080" 40 3 || true

  # ── Summary ───────────────────────────────────────────────────────────────────
  section "Installation complete"
  echo ""
  echo -e "  ${GREEN}${BOLD}MailDome is running.${NC}"
  echo ""
  echo "  API endpoint : http://localhost:8080"
  echo "  Health check : http://localhost:8080/api/v1/status"
  echo ""
  echo -e "  ${BOLD}API token (needed for the Thunderbird plugin):${NC}"
  echo -e "  ${YELLOW}${API_TOKEN}${NC}"
  echo ""
  echo "  Configure the Thunderbird plugin:"
  echo "    Server URL : http://$(hostname -I | awk '{print $1}' 2>/dev/null || echo 'YOUR_SERVER_IP'):8080"
  echo "    API Token  : (shown above)"
  echo ""
  echo "  Useful commands:"
  echo "    $COMPOSE logs -f           — stream all logs"
  echo "    $COMPOSE logs -f api       — API logs only"
  echo "    $COMPOSE ps                — container status"
  echo "    $COMPOSE down              — stop all services"
  echo ""
  echo -e "  ${DIM}Your .env contains all secrets. Back it up securely."
  echo -e "  Never commit .env or docker-compose.override.yml to git.${NC}"
  echo ""
}

# ── Entry point ───────────────────────────────────────────────────────────────
if [[ "$_MAILDOME_TEST" != "1" ]]; then
  main "$@"
fi
