#!/usr/bin/env bash
# tests/test_install.sh — Unit tests for install.sh pure functions.
#
# Run with:  bash tests/test_install.sh
#
# Sources install.sh in test mode (MAILDOME_TEST=1) so only function
# definitions are loaded — no interactive prompts, no docker calls.

set -euo pipefail

PASS=0; FAIL=0

# ── Test harness ──────────────────────────────────────────────────────────────

assert_eq() {
  local desc="$1" expected="$2" actual="$3"
  if [[ "$expected" == "$actual" ]]; then
    echo "  PASS  $desc"
    PASS=$(( PASS + 1 ))
  else
    echo "  FAIL  $desc"
    echo "        expected: $(echo "$expected" | head -3)"
    echo "        actual:   $(echo "$actual"   | head -3)"
    FAIL=$(( FAIL + 1 ))
  fi
}

assert_contains() {
  local desc="$1" needle="$2" haystack="$3"
  if echo "$haystack" | grep -qF "$needle"; then
    echo "  PASS  $desc"
    PASS=$(( PASS + 1 ))
  else
    echo "  FAIL  $desc"
    echo "        expected to contain: $needle"
    echo "        actual: $(echo "$haystack" | head -5)"
    FAIL=$(( FAIL + 1 ))
  fi
}

assert_not_contains() {
  local desc="$1" needle="$2" haystack="$3"
  if ! echo "$haystack" | grep -qF "$needle"; then
    echo "  PASS  $desc"
    PASS=$(( PASS + 1 ))
  else
    echo "  FAIL  $desc"
    echo "        expected NOT to contain: $needle"
    FAIL=$(( FAIL + 1 ))
  fi
}

# ── Load functions without running main ───────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAILDOME_TEST=1 source "$SCRIPT_DIR/install.sh"

echo ""
echo "Running install.sh unit tests"
echo "══════════════════════════════"

# ── recommend_tier ────────────────────────────────────────────────────────────

echo ""
echo "recommend_tier"

assert_eq "small + no exec → Basic" \
  "Basic" "$(recommend_tier small n)"

assert_eq "small + exec → Advanced" \
  "Advanced" "$(recommend_tier small y)"

assert_eq "medium + no exec → Advanced" \
  "Advanced" "$(recommend_tier medium n)"

assert_eq "medium + exec → Advanced" \
  "Advanced" "$(recommend_tier medium y)"

assert_eq "large + no exec → Advanced" \
  "Advanced" "$(recommend_tier large n)"

assert_eq "large + exec → Premium" \
  "Premium" "$(recommend_tier large y)"

# ── gen_secret ────────────────────────────────────────────────────────────────

echo ""
echo "gen_secret"

SECRET=$(gen_secret 16)
assert_eq "default 32-byte secret is 64 hex chars" \
  "64" "$(gen_secret 32 | tr -d '\n' | wc -c | tr -d ' ')"

assert_eq "16-byte secret is 32 hex chars" \
  "32" "$(gen_secret 16 | tr -d '\n' | wc -c | tr -d ' ')"

# Two calls should (almost certainly) produce different values
SECRET_A=$(gen_secret 32)
SECRET_B=$(gen_secret 32)
if [[ "$SECRET_A" != "$SECRET_B" ]]; then
  echo "  PASS  gen_secret produces unique values"
  (( PASS++ ))
else
  echo "  FAIL  gen_secret returned identical values twice"
  (( FAIL++ ))
fi

# ── write_env ─────────────────────────────────────────────────────────────────

echo ""
echo "write_env"

TMP_ENV=$(mktemp)
write_env "$TMP_ENV" \
  POSTGRES_PASSWORD "s3cr3t" \
  REDIS_PASSWORD    "r3d1s" \
  API_TOKEN         "tok123"
ENV_CONTENT=$(cat "$TMP_ENV")
rm -f "$TMP_ENV"

assert_contains "write_env: POSTGRES_PASSWORD present" \
  "POSTGRES_PASSWORD=s3cr3t" "$ENV_CONTENT"

assert_contains "write_env: REDIS_PASSWORD present" \
  "REDIS_PASSWORD=r3d1s" "$ENV_CONTENT"

assert_contains "write_env: API_TOKEN present" \
  "API_TOKEN=tok123" "$ENV_CONTENT"

assert_contains "write_env: header comment present" \
  "generated by install.sh" "$ENV_CONTENT"

# ── patch_conf ────────────────────────────────────────────────────────────────

echo ""
echo "patch_conf"

TMP_CONF=$(mktemp)
cat > "$TMP_CONF" <<'CONF'
[acquisition]
imap_host = mail.example.com
imap_port = 993
imap_user = scanner@example.com

[notifications]
admin_email =
CONF

patch_conf "$TMP_CONF" acquisition imap_host "mail.company.com"
CONF_CONTENT=$(cat "$TMP_CONF")

assert_contains "patch_conf: imap_host updated" \
  "imap_host = mail.company.com" "$CONF_CONTENT"

assert_not_contains "patch_conf: old value removed" \
  "imap_host = mail.example.com" "$CONF_CONTENT"

assert_contains "patch_conf: other keys unchanged" \
  "imap_port = 993" "$CONF_CONTENT"

patch_conf "$TMP_CONF" notifications admin_email "admin@company.com"
CONF_CONTENT2=$(cat "$TMP_CONF")
assert_contains "patch_conf: admin_email set" \
  "admin_email = admin@company.com" "$CONF_CONTENT2"

# Patching a key outside the targeted section must not change it
patch_conf "$TMP_CONF" acquisition imap_user "new@company.com"
CONF_CONTENT3=$(cat "$TMP_CONF")
assert_contains "patch_conf: correct section updated" \
  "imap_user = new@company.com" "$CONF_CONTENT3"
assert_contains "patch_conf: adjacent section untouched" \
  "admin_email = admin@company.com" "$CONF_CONTENT3"

rm -f "$TMP_CONF"

# ── write_override ────────────────────────────────────────────────────────────

echo ""
echo "write_override"

TMP_OVR=$(mktemp)
write_override "$TMP_OVR" "company.com" "/app/core/config/mailshield.conf"
OVR_CONTENT=$(cat "$TMP_OVR")
rm -f "$TMP_OVR"

assert_contains "write_override: mail domain present" \
  "company.com" "$OVR_CONTENT"

assert_contains "write_override: MAILSHIELD_CONFIG path present" \
  "/app/core/config/mailshield.conf" "$OVR_CONTENT"

assert_contains "write_override: api service present" \
  "api:" "$OVR_CONTENT"

assert_contains "write_override: celery_worker service present" \
  "celery_worker:" "$OVR_CONTENT"

assert_contains "write_override: API_TOKEN forwarded" \
  "API_TOKEN=" "$OVR_CONTENT"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "══════════════════════════════"
TOTAL=$(( PASS + FAIL ))
echo "Results: ${PASS}/${TOTAL} passed"
echo ""

if (( FAIL > 0 )); then
  exit 1
fi
